/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ProviderRole;

import Business.Enterprise.Enterprise;
import Business.Organization.ProviderOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author shruti
 */
public class ProviderWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProviderWorkAreaJPanel
     */
    
    private JPanel userProcessContainer;
    private ProviderOrganization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    public ProviderWorkAreaJPanel(JPanel userProcessContainer,UserAccount userAccount,ProviderOrganization organization,Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;                                                        //EmployeeDirectory manufacturerDirectory
        this.userAccount = userAccount;
        organization = (ProviderOrganization)organization;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        browseElectricityJButton = new javax.swing.JButton();
        viewOrderHistoryJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        requestSmartMeterJButton = new javax.swing.JButton();
        customerRequestsJButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 204));

        browseElectricityJButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        browseElectricityJButton.setText("Browse Electricity Source Tarrifs");
        browseElectricityJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseElectricityJButtonActionPerformed(evt);
            }
        });

        viewOrderHistoryJButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        viewOrderHistoryJButton.setText("View Order History");
        viewOrderHistoryJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewOrderHistoryJButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("                                    PROVIDER WORK AREA");

        requestSmartMeterJButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        requestSmartMeterJButton.setText("Request SmartMeter");
        requestSmartMeterJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestSmartMeterJButtonActionPerformed(evt);
            }
        });

        customerRequestsJButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        customerRequestsJButton.setText("Manage Customer Requests");
        customerRequestsJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerRequestsJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 103, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(customerRequestsJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(requestSmartMeterJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewOrderHistoryJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(browseElectricityJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(browseElectricityJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(viewOrderHistoryJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(requestSmartMeterJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(customerRequestsJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(119, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void browseElectricityJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseElectricityJButtonActionPerformed
        // TODO add your handling code here:                                               //organization
        BrowseElectricityForAppliancesJPanel bvjp = new BrowseElectricityForAppliancesJPanel(userProcessContainer,userAccount,organization,enterprise);  //mo  //manufacturerDirectory
        userProcessContainer.add("BrowseVaccinesJPanel",bvjp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_browseElectricityJButtonActionPerformed

    private void viewOrderHistoryJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewOrderHistoryJButtonActionPerformed
        // TODO add your handling code here:
        ViewOrderHistoryJPanel viewOrderHistoryJPanel = new ViewOrderHistoryJPanel(userProcessContainer,userAccount);
        userProcessContainer.add("viewOrderHistoryJPanel",viewOrderHistoryJPanel);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_viewOrderHistoryJButtonActionPerformed

    private void requestSmartMeterJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestSmartMeterJButtonActionPerformed
        // TODO add your handling code here:
        RequestSmartMeterJPanel rjp = new RequestSmartMeterJPanel(userProcessContainer,enterprise,userAccount);
        userProcessContainer.add("RequestPHDJPanel",rjp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_requestSmartMeterJButtonActionPerformed

    private void customerRequestsJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerRequestsJButtonActionPerformed
        // TODO add your handling code here:
        ManageCustomerRequestsJPanel mhjp = new ManageCustomerRequestsJPanel(userProcessContainer, userAccount,enterprise);
        userProcessContainer.add("RequestPHDJPanel",mhjp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_customerRequestsJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton browseElectricityJButton;
    private javax.swing.JButton customerRequestsJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton requestSmartMeterJButton;
    private javax.swing.JButton viewOrderHistoryJButton;
    // End of variables declaration//GEN-END:variables
}
