/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.TransmissionNetworkRole;

import Business.Enterprise.Enterprise;
import Business.Organization.TransmissionNetworkOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author shruti
 */
public class TransmissionNetworkWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form TransmissionNetworkWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private Enterprise enterprise;
    private TransmissionNetworkOrganization organization;
    public TransmissionNetworkWorkAreaJPanel(JPanel userProcessContainer,UserAccount userAccount,TransmissionNetworkOrganization organization,Enterprise enterprise) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.enterprise = enterprise;
        organization = (TransmissionNetworkOrganization)organization;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        manageShippingRequestsJButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 204));

        manageShippingRequestsJButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        manageShippingRequestsJButton.setText("Manage Shipping Requests");
        manageShippingRequestsJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageShippingRequestsJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(manageShippingRequestsJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(133, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(manageShippingRequestsJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(254, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void manageShippingRequestsJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageShippingRequestsJButtonActionPerformed
        // TODO add your handling code here:
        ManageOrderRequestJPanel mhjp = new ManageOrderRequestJPanel(userProcessContainer,userAccount,enterprise);
        userProcessContainer.add("ManageHospitalRequests",mhjp);
        ((CardLayout)userProcessContainer.getLayout()).next(userProcessContainer);

    }//GEN-LAST:event_manageShippingRequestsJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton manageShippingRequestsJButton;
    // End of variables declaration//GEN-END:variables
}
