spring:
  jpa:
    hibernate:
      ddl-auto: none
  social:
    facebook:
      appId: 172325543698104
      appSecret: 2680e61473dd01f0d9a91c12fe22368d
  thymeleaf:
    cache: false


security:
  oauth2:
    client:
      clientId: 172325543698104
      clientSecret: 2680e61473dd01f0d9a91c12fe22368d
      accessTokenUri: https://graph.facebook.com/oauth/access_token
      userAuthorizationUri: https://www.facebook.com/dialog/oauth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://graph.facebook.com/me
