/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.PowerStationAdminRole;

import Business.Enterprise.Enterprise;
import Business.Organization.PowerStationOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author shruti
 */
public class PowerStationWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
   
    private UserAccount userAccount;
    
    private Enterprise enterprise;
    private PowerStationOrganization organization;
    /**
     * Creates new form PowerStationWorkAreaJPanel
     */
    public PowerStationWorkAreaJPanel(JPanel userProcessContainer,UserAccount userAccount,PowerStationOrganization organization,Enterprise enterprise) {
        initComponents();
         this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.organization = (PowerStationOrganization)organization;
        this.enterprise = enterprise;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        manageElectricityJButton = new javax.swing.JButton();
        smartMeterEnrollmentJButton = new javax.swing.JButton();
        electricityJButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 204));

        manageElectricityJButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        manageElectricityJButton.setText("Manage Stored Electricity");
        manageElectricityJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageElectricityJButtonActionPerformed(evt);
            }
        });

        smartMeterEnrollmentJButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        smartMeterEnrollmentJButton.setText("Grid Energy Storage Enrollment");
        smartMeterEnrollmentJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smartMeterEnrollmentJButtonActionPerformed(evt);
            }
        });

        electricityJButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        electricityJButton.setText("Review Electricity Source Performance");
        electricityJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                electricityJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(187, 187, 187)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(electricityJButton, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
                    .addComponent(smartMeterEnrollmentJButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(manageElectricityJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(130, 130, 130))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(manageElectricityJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(114, 114, 114)
                .addComponent(smartMeterEnrollmentJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(165, 165, 165)
                .addComponent(electricityJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(181, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void manageElectricityJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageElectricityJButtonActionPerformed
        // TODO add your handling code here:

        ManageElectricityJPanel mvjp = new ManageElectricityJPanel(userProcessContainer,organization );      //organization
        userProcessContainer.add("ManageVaccineCatalogJPanel",mvjp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_manageElectricityJButtonActionPerformed

    private void smartMeterEnrollmentJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smartMeterEnrollmentJButtonActionPerformed
        // TODO add your handling code here:
        GridEnergyStorageEnrollmentJPanel warehouseEnrollmentJPanel = new GridEnergyStorageEnrollmentJPanel(userProcessContainer, userAccount,organization,enterprise); //enterprise
        userProcessContainer.add("enrollmentRequestJPanel",warehouseEnrollmentJPanel);                     //organization
        ((CardLayout)userProcessContainer.getLayout()).next(userProcessContainer);
    }//GEN-LAST:event_smartMeterEnrollmentJButtonActionPerformed

    private void electricityJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_electricityJButtonActionPerformed
        // TODO add your handling code here:
        ReviewPerformanceJPanel rvjp = new ReviewPerformanceJPanel(userProcessContainer, organization, enterprise);
        userProcessContainer.add("ReviewVaccineJPanel",rvjp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_electricityJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton electricityJButton;
    private javax.swing.JButton manageElectricityJButton;
    private javax.swing.JButton smartMeterEnrollmentJButton;
    // End of variables declaration//GEN-END:variables
}
